"""initial_schema

Revision ID: 1f2d61af3b1a
Revises: 
Create Date: 2026-07-10 23:11:08.538758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f2d61af3b1a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('failed_at_stage', sa.String(length=32), nullable=True),
    sa.Column('mineru_output_dir', sa.Text(), nullable=True),
    sa.Column('questions_found', sa.Integer(), nullable=False),
    sa.Column('questions_saved', sa.Integer(), nullable=False),
    sa.Column('detected_layout', sa.String(length=64), nullable=True),
    sa.Column('detected_subjects', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_time_s', sa.Float(), nullable=True),
    sa.Column('processing_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('papers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('blueprint', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingestion_id', sa.UUID(), nullable=False),
    sa.Column('source_pdf', sa.Text(), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('question_number', sa.Integer(), nullable=True),
    sa.Column('stem_md', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('section_type', sa.String(length=16), nullable=False),
    sa.Column('section_label', sa.String(length=32), nullable=True),
    sa.Column('exam_name', sa.Text(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('chapter', sa.Text(), nullable=True),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('subtopic', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=16), nullable=True),
    sa.Column('question_type', sa.Text(), nullable=True),
    sa.Column('concepts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('has_diagram', sa.Boolean(), nullable=False),
    sa.Column('has_formula', sa.Boolean(), nullable=False),
    sa.Column('llm_raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_id'], ['ingestions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_q_chapter', 'questions', ['chapter'], unique=False)
    op.create_index('idx_q_difficulty', 'questions', ['difficulty'], unique=False)
    op.create_index('idx_q_exam', 'questions', ['exam_name'], unique=False)
    op.create_index('idx_q_ingestion', 'questions', ['ingestion_id'], unique=False)
    op.create_index('idx_q_status', 'questions', ['status'], unique=False)
    op.create_index('idx_q_subject', 'questions', ['subject'], unique=False)
    op.create_table('paper_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('paper_section', sa.String(length=32), nullable=True),
    sa.Column('display_number', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'position', name='uq_paper_position'),
    sa.UniqueConstraint('paper_id', 'question_id', name='uq_paper_question')
    )
    op.create_index('idx_pq_paper', 'paper_questions', ['paper_id'], unique=False)
    op.create_index('idx_pq_position', 'paper_questions', ['paper_id', 'position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_pq_position', table_name='paper_questions')
    op.drop_index('idx_pq_paper', table_name='paper_questions')
    op.drop_table('paper_questions')
    op.drop_index('idx_q_subject', table_name='questions')
    op.drop_index('idx_q_status', table_name='questions')
    op.drop_index('idx_q_ingestion', table_name='questions')
    op.drop_index('idx_q_exam', table_name='questions')
    op.drop_index('idx_q_difficulty', table_name='questions')
    op.drop_index('idx_q_chapter', table_name='questions')
    op.drop_table('questions')
    op.drop_table('papers')
    op.drop_table('ingestions')
    # ### end Alembic commands ###
