"""add_exam_name_subject_layout_type_to_ingestions

Revision ID: 37fb3c0644f7
Revises: 1f2d61af3b1a
Create Date: 2026-07-11 01:41:31.800597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37fb3c0644f7'
down_revision: Union[str, Sequence[str], None] = '1f2d61af3b1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingestions', sa.Column('exam_name', sa.Text(), nullable=True))
    op.add_column('ingestions', sa.Column('subject', sa.Text(), nullable=True))
    op.add_column('ingestions', sa.Column('layout_type', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingestions', 'layout_type')
    op.drop_column('ingestions', 'subject')
    op.drop_column('ingestions', 'exam_name')
    # ### end Alembic commands ###
